# Book settings
title: LCG - Machine Learning
author: Learn Computer Graphics team
logo: logo.png

repository:
  url: https://github.com/learn-computer-graphics/machine-learning

html:
  favicon : "favicon.ico"
  use_issues_button: true
  use_repository_button: true
